repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.7
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-check
      args: [ --select=I, --fix ]
    - id: ruff-format
