[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "torch-max-backend"
version = "0.2.0"
description = "A PyTorch backend implemented using Modular's MAX framework"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "max[serve]",
    "tabulate",
    "torch",
    "beartype>=0.17.0",
]

[project.urls]
"Source" = "https://github.com/gabrieldemarmiesse/torch-max-backend"
"Documentation" = "https://gabrieldemarmiesse.github.io/torch-max-backend/"
"Bug Tracker" = "https://github.com/gabrieldemarmiesse/torch-max-backend/issues"

[tool.hatch.build.targets.wheel]
packages = ["torch_max_backend"]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = [
    "F",  # pyflakes (includes unused imports)
    "UP", # pyupgrade
]

[tool.uv.sources]
max = [
    { index = "modular-nightly" },
]
mblack = [
    { index = "modular-nightly" },
]
max-core = [
    { index = "modular-nightly" },
]
mojo-compiler = [
    { index = "modular-nightly" },
]

[[tool.uv.index]]
name = "modular-nightly"
url = "https://dl.modular.com/public/nightly/python/simple/"
explicit = true

[tool.uv]
prerelease = "allow"


[tool.ruff.format]
skip-magic-trailing-comma = true

[dependency-groups]
dev = [
    # Bump the version of max nightly here
    "mblack==25.6.0.dev2025090805",
    "max==25.6.0.dev2025090805",
    "max-core==25.6.0.dev2025090805",
    "mojo-compiler==0.25.6.0.dev2025090805",
    "accelerate>=1.10.0",
    "hatchling",
    "ibm-fms>=1.2.1",
]

